### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by aurnoi1** [mobily-enterprises/docco-next#13]
Hi,

May you provide an example of configuration to have highlighted code (javascript) in the output markdown please?

```gherkin
Given I have a javascript file "example.js" with documentation inside
When I generate the documentation with the following command:
    docco.sh -o ./doc -l plain -x md ./example.js
Then the generated markdown should contain the following code block:
    ```javascript
    const a = 3;
    ```
And the code block should be highlighted once the markdown rendered
````

Thanks!

**Comment by mercmobily** [comment]
Cab you please provide an 'example.js' file that *should* work and doesn't?

**Comment by aurnoi1** [comment]
This is an example of code:

```javascript
const chai = require('chai');
const persona = require('../utils/persona.js');
chai.should();

describe('Create an persona', () => {
  it.only('should work', async () => {
    // Create a persona
    const user = persona.create();

    // Check it is defined
    user.should.not.equal(undefined);
  });
});
```

When I execute ```docco.sh -o ./doc -l plain -x md ./example.js```, I get this actual document: 
[actual.md](https://github.com/mobily-enterprises/docco-next/files/6357508/actual.md), when I am expecting this [expected.md](https://github.com/mobily-enterprises/docco-next/files/6357509/expected.md).

**Comment by mercmobily** [comment]
This was a bug. I fixed it in the latest release.
Please confirm that fix worked.

**Comment by mercmobily** [comment]
...?

**Comment by aurnoi1** [comment]
Sorry I was off. Yes I confirm it works with the version 0.9.8. Thanks!

**Comment by mercmobily** [comment]
Fantastic -- thanks!
