### ISSUE TITLE
Complete examples?

### ISSUE THREAD

**Issue by ange007** [mobily-enterprises/docco-next#5]
Hello.
I try use this lib but nothing works out for me.

`docco "backend/api/controllers/*php" -l "parallel" -o "docs/d"`
Result: `docco: file not processed, language not supported: (*php)`

How use it?

**Comment by mercmobily** [comment]
I suspect the problem here might be in the way you are running the command line. Writing ""backend/api/controllers/*php" will prevent bash's wildcard expansion. So, docco-next is looking for a file called `backend/api/controllers/*php`.

Can you try without brackets?

**Comment by ange007** [comment]
[image: image.png]

вт, 25 февр. 2020 г. в 23:07, Tony Mobily <notifications@github.com>:

**Comment by ange007** [comment]
![image](https://user-images.githubusercontent.com/2736539/75288445-0dfdea00-5825-11ea-94e8-98b26b635ac5.png)

I try on Windows 10, Node 10.13.0

**Comment by mercmobily** [comment]
Are you sure you have php files in there?
This is what I am seeing:

````
$ ls -l A/backend/api/controllers/
total 8
-rw-r--r-- 1 merc merc 7 Feb 26 05:23 one.php
-rw-r--r-- 1 merc merc 7 Feb 26 05:24 two.php
$ ls -l B
total 0
$ bin/docco A/backend/api/controllers/*php -l "parallel" -o "B"
docco: A/backend/api/controllers/one.php ->
B/A/backend/api/controllers/one.html
docco: A/backend/api/controllers/two.php ->
B/A/backend/api/controllers/two.html
````

Then I tried with only one file in the directory:

````
$ rm A/backend/api/controllers/one.php
$ bin/docco A/backend/api/controllers/*php -l "parallel" -o "B"
docco: A/backend/api/controllers/two.php ->
B/A/backend/api/controllers/two.html
$
````

Then with zero files:

````
$ rm A/backend/api/controllers/two.php
$ bin/docco A/backend/api/controllers/*php -l "parallel" -o "B"
docco: file not processed, language not supported: (*php)
$
````

There you are!

**Comment by ange007** [comment]
Hello.
Files are present.
![image](https://user-images.githubusercontent.com/2736539/75348794-21a06380-58ac-11ea-8ca8-0a4c17d72a64.png)

**Comment by mercmobily** [comment]
I missed that you are on Windows.
Can you run the same commands as your initial comments, but with `ls` or `dir` instead of `docco`?
I am sorry, I don't use Windows and I am not 100% sure if this is a Windows problem or (most likely) a Docco-Next problem (as in, I am not dealing with paths properly)

**Comment by ange007** [comment]
Yes
![image](https://user-images.githubusercontent.com/2736539/75390348-d197c000-58f0-11ea-9370-85634f810d25.png)

**Comment by mercmobily** [comment]
Please use the exact same pat hstring. You missed the *php in the ls
command.

**Comment by ange007** [comment]
Sorry.
![image](https://user-images.githubusercontent.com/2736539/75391361-9c8c6d00-58f2-11ea-95f6-e1b6d7eeffe7.png)

**Comment by mercmobily** [comment]
And now the exact same command but with `docco` instead of `ls` -- in the same directory, same path, same everything?

**Comment by ange007** [comment]
![image](https://user-images.githubusercontent.com/2736539/75467408-43751580-5994-11ea-9452-a8e48f8a0f5c.png)

In the Linux subsystem (on Windows) the same situation, tomorrow I’ll try to check on Linux Mint.
![image](https://user-images.githubusercontent.com/2736539/75467690-b4b4c880-5994-11ea-9dc1-4523dedd5a75.png)

**Comment by mercmobily** [comment]
I only have a Windows machine for gaming. I *can* install node on it. What else do you have installed? Where does Windows get the "ls" command from?
I wonder if I make a mistake in the way I treat paths in Windows.

**Comment by ange007** [comment]
I try on Linux - the same result.

![image](https://user-images.githubusercontent.com/2736539/75541862-4a993380-5a27-11ea-859f-76459fdd2789.png)

![image](https://user-images.githubusercontent.com/2736539/75541922-70263d00-5a27-11ea-9742-e8bfc5f3f2b4.png)

![image](https://user-images.githubusercontent.com/2736539/75541945-816f4980-5a27-11ea-8796-f3fc3a096051.png)

![image](https://user-images.githubusercontent.com/2736539/75541898-5b49a980-5a27-11ea-8f17-bbcc1585e0b4.png)

**Comment by mercmobily** [comment]
This is insane. Please accept my apologies for not supporting you properly.
As one last resort, can you please send me a tgz or zip with the contents of the "controllers" directory either here in the issue, or -- if it's private -- to my email tonymobily@gmail.com ?

Please make sure the directory structure is the same.

I will get to the bottom of this!

**Comment by mercmobily** [comment]
Wait no need to send me an attachment.
Please have a look here:

````
merc@merc-All-Series:~$ mkdir -p application/backend/api/controllers
merc@merc-All-Series:~$ echo "some code" > application/backend/api/controllers/ApiBaseController.php
merc@merc-All-Series:~$ echo "some other code" > application/backend/api/controllers/OtherBaseController.php
merc@merc-All-Series:~$ cd application/
merc@merc-All-Series:~/application$ ../Development/docco-next/bin/docco "backend/api/controllers/*php"
docco: file not processed, language not supported: (*php)
merc@merc-All-Series:~/application$ ../Development/docco-next/bin/docco backend/api/controllers/*php
docco: backend/api/controllers/ApiBaseController.php -> docs/backend/api/controllers/ApiBaseController.html
docco: backend/api/controllers/OtherBaseController.php -> docs/backend/api/controllers/OtherBaseController.html
merc@merc-All-Series:~/application$ 
````
So, it will work without the brackets:

````
docco backend/api/controllers/*php
````

**Comment by ange007** [comment]
No, its not work :(
Mayme that the reason is the start by alias?

**Comment by mercmobily** [comment]
What is your alias?

**Comment by ange007** [comment]
> What is your alias?

Im talk about: `../Development/docco-next/bin/docco = docco`
Can there be errors when determining the path when making a call not directly, but through an alias in NPM?

Is there any kind of debugging mode?

**Comment by mercmobily** [comment]
Wait good point. Let me try something.

**Comment by mercmobily** [comment]
Nope. I installed it with -g, and it still all works.

````
merc@merc-All-Series:~/application$ ls -l backend/api/controllers/
total 8
-rw-r--r-- 1 merc merc 10 Feb 28 20:04 ApiBaseController.php
-rw-r--r-- 1 merc merc 16 Feb 28 20:04 OtherBaseController.php
merc@merc-All-Series:~/application$
merc@merc-All-Series:~/application$ docco backend/api/controllers/*php
docco: backend/api/controllers/ApiBaseController.php -> docs/backend/api/controllers/ApiBaseController.html
docco: backend/api/controllers/OtherBaseController.php -> docs/backend/api/controllers/OtherBaseController.html
merc@merc-All-Series:~/application$ 
````

**Comment by ange007** [comment]
It is very strange.
What am I doing wrong?

**Comment by mercmobily** [comment]
@freudFlintstone  any ideas?

**Comment by mercmobily** [comment]
I am sorry, I am not sure how to help here. It doesn't seem to make sense! I am leaving it open in the hope that somebody will pick it up.

@ange007 Did you discover anything else?

**Comment by mercmobily** [comment]
Did you work out what was going on?

**Comment by ange007** [comment]
Hello, no.
It was decided to switch to other solutions unfortunately.

**Comment by mercmobily** [comment]
I am sorry, this is a real mystery and can't solve it without further reporting from you. Closing.
